spring:
  application:
    name: "dataset-collector"
  data:
    mongodb:
      host: localhost
      port: 27017
      database: ledokol
      username: root
      password: example
      authentication-database: admin
      auto-index-creation: true
prometheus:
  url: 'http://localhost:9090'
server:
  port: 8084
