apiVersion: v1
kind: ConfigMap
metadata:
  name: generator-config
  labels:
    app: generator
data:
  config.yaml: |
    logging:
      level: info
      file: ./logs/server.log
      max-file-size: 5
      max-backups: 10
      max-age: 14
      compress-rotated-log: true
      time-format: "2006-01-02 15:04:05.000"
    consul:
      address: ledokol-config-consul-server:8500
      check:
        interval: 15s
        timeout: 10s
      tags: ["prometheus_monitoring_endpoint=/metrics"]
      main-service-id: ledokol-main